import { v4 as uuid } from "uuid";

export const products = [
  {
    _id: "ff4c5d0f-98c7-46ac-83fd-48190224f568",
    index: 1,
    image:
      "https://images.bewakoof.com/t1080/men-s-black-military-flip-flops-sliders-393534-1655816733-1.jpg",
    category: "Men",
    rating: 4,
    size: 8,
    title: "Pampy Angel",
    description: "Men's Black Military Flip Flops & Sliders",
    trending: true,
    orig_price: 799,
    sell_price: 359,
    delivery_days: 5,
    in_stock: true,
  },
  {
    _id: "50b0450d-339c-4999-a980-3fcdcf0a82df",
    index: 2,
    image:
      "https://imagescdn.planetfashion.in/img/app/product/6/660245-6736194.jpg?auto=format",
    category: "Men",
    rating: 3.5,
    size: 9,
    title: "Men Yellow Flip Flops",
    description:
      "Add a spunky edge to your relaxed style with these yellow Flip-Flops",
    trending: false,
    orig_price: 999,
    sell_price: 699,
    delivery_days: 6,
    in_stock: true,
  },
  {
    _id: "64833894-d6b0-4f81-9589-48949509d0df",
    index: 3,
    image:
      "https://assets.ajio.com/medias/sys_master/root/20220616/nFMb/62ab146eaeb26921af2c0f63/-473Wx593H-464277355-grey-MODEL6.jpg",
    category: "Men",
    rating: 4.5,
    size: 8,
    title: "HUMMEL",
    description: "Flip Flops with Synthetic upper",
    trending: true,
    orig_price: 999,
    sell_price: 599,
    delivery_days: 5,
    in_stock: false,
  },
  {
    _id: "88bdd9f5-5295-4fe8-b54b-a5540b59541d",
    index: 4,
    image:
      "https://mirzacdns3.s3.ap-south-1.amazonaws.com/cache/catalog/RFF1027/8-800x800.jpg",
    category: "Men",
    rating: 5,
    size: 10,
    title: "Sliders Slippers For Men | Comfortable Slip-Ons",
    description:
      "Enjoy Your Walk & Leisure Activities With These Ice-Grey Color Slip-Ons Closure Sliders Slippers",
    trending: true,
    orig_price: 2199,
    sell_price: 659,
    delivery_days: 7,
    in_stock: true,
  },
  {
    _id: "e552fc71-89be-4b7b-9579-f0d87dc039d1",
    index: 5,
    image:
      "https://5.imimg.com/data5/SELLER/Default/2023/3/293810049/MW/SG/VH/185476700/whatsapp-image-2021-12-02-at-8-20-10-pm-1--500x500.jpeg",
    category: "Men",
    rating: 3,
    size: 8,
    title:
      "Printed Black nike slider for men flip flop men slippers and chappal",
    description: "Best product in this price",
    trending: false,
    orig_price: 300,
    sell_price: 250,
    delivery_days: 4,
    in_stock: true,
  },
  {
    _id: "953030a9-30a8-432f-9cc6-b9bd1bfe4040",
    index: 6,
    image:
      "https://contents.mediadecathlon.com/p1289066/0f0771c9a7908de0dce302f83497df6d/p1289066.jpg?format=auto&quality=70&f=650x0",
    category: "Men",
    rating: 3.5,
    size: 7,
    title: "Men Flip-Flops 120 Floral Blue",
    description:
      "Our surfer design teams have developed these Flip-Flops for people practising water sports “before and after their sessions”. Suitable for everyone!",
    trending: true,
    orig_price: 199,
    sell_price: 99,
    delivery_days: 3,
    in_stock: true,
  },
  {
    _id: "3dcdbf50-e09b-4b81-8f35-cbd0834cd129",
    index: 7,
    image:
      "https://imagescdn.planetfashion.in/img/app/product/5/586904-5335408.jpg?auto=format",
    category: "Men",
    rating: 4.5,
    size: 9,
    title: "Men White Solid Flip Flops",
    description:
      "Slip into your comfort zone with these white flip-flops. With excellent support and a cushioned foot bed, these flip-flops are stylishly attractive, all the while providing unmatched comfort.",
    trending: true,
    orig_price: 1699,
    sell_price: 1019,
    delivery_days: 6,
    in_stock: false,
  },
  {
    _id: "9305e24e-f627-4d37-a527-aee8add34f8d",
    index: 8,
    image:
      "https://dxkvlfvncvqr8.cloudfront.net/media/product-image/BHG-151-NVWH-1.jpg",
    category: "Men",
    rating: 2.5,
    size: 6,
    title: "Flip flops for men",
    description:
      "You'll love fit and comfort of this flip-flop. Grooving on side to enhance your style quotient.",
    trending: false,
    orig_price: 350,
    sell_price: 279,
    delivery_days: 3,
    in_stock: true,
  },
  {
    _id: "36d685ec-3028-411c-b0c6-d0eab18fcb1e",
    index: 9,
    image:
      "https://sslimages.shoppersstop.com/sys-master/images/hf7/hd4/28787262881822/FMJJ2490823_WHITE.jpg_2000Wx3000H",
    category: "Men",
    rating: 4,
    size: 8,
    title: "Jack And Jones",
    description: "JFW Chuck Polyurethane Slipon Mens Slides",
    trending: true,
    orig_price: 1999,
    sell_price: 599,
    delivery_days: 7,
    in_stock: true,
  },
  {
    _id: "fa61ff13-f09a-4702-b457-14601319e141",
    index: 10,
    image:
      "https://images.bewakoof.com/t1080/sliding-bat-lightweight-adjustable-strap-men-slider-367177-1655748693-3.jpg",
    category: "Men",
    rating: 5,
    size: 9,
    title: "OFFICIAL DC COMICS MERCHANDISE",
    description: "Sliding Bat Lightweight Adjustable Strap Men Slider",
    trending: true,
    orig_price: 1099,
    sell_price: 649,
    delivery_days: 3,
    in_stock: false,
  },
  {
    _id: "b445f833-1176-4305-9c34-3b169f6fbd39",
    index: 11,
    image:
      "https://assets.ajio.com/medias/sys_master/root/20220704/ByTr/62c2fb63aeb26921af5ee3ef/-473Wx593H-469136105-black-MODEL5.jpg",
    category: "Women",
    rating: 3,
    size: 7,
    title: "PUMA",
    description: "Tropical Print T-strap Flip-Flops",
    trending: true,
    orig_price: 799,
    sell_price: 503,
    delivery_days: 10,
    in_stock: true,
  },
  {
    _id: "718ab2aa-1e78-4426-8fed-d0f9ff29fd4c",
    index: 12,
    image: "https://images.meesho.com/images/products/112433517/y6qgg_512.webp",
    category: "Women",
    rating: 4,
    size: 6,
    title: "Peach Soft Flats For Women Flip Flops For Woman ",
    description:
      "Footwear Flats Sandals Women Flip Flops Fancy Daily Use Slipper Stylish Party Wear Chappals Latest Fashion Casual Ladies Flat Sandals",
    trending: false,
    orig_price: 320,
    sell_price: 280,
    delivery_days: 4,
    in_stock: true,
  },
  {
    _id: "fec89f9c-a5f9-459c-8096-810b474ab3e3",
    index: 13,
    image:
      "https://images.bewakoof.com/t1080/daisy-petal-adjustable-velcro-women-s-slider-585164-1680612744-2.jpg",
    category: "Women",
    rating: 5,
    size: 7,
    title: "Bewakoof",
    description: "Women's Blue Daisy Petal Adjustable Velcro Sliders",
    trending: true,
    orig_price: 999,
    sell_price: 499,
    delivery_days: 6,
    in_stock: true,
  },
  {
    _id: "194714dc-13c1-4fde-9032-bf8b033658be",
    index: 14,
    image:
      "https://rukminim1.flixcart.com/image/832/832/xif0q/slipper-flip-flop/4/y/z/5-wo-201-white-monoction-white-original-imagh7efjtuvdtav.jpeg?q=70",
    category: "Women",
    rating: 3.5,
    size: 5,
    title: "White Slides for Girls",
    description:
      "premium Quality New look flip flops slides for girls & women Slides ",
    trending: true,
    orig_price: 999,
    sell_price: 284,
    delivery_days: 2,
    in_stock: false,
  },
  {
    _id: "bb96174e-b038-4a98-8cc1-1fe5eeae4aa9",
    index: 15,
    image:
      "https://contents.mediadecathlon.com/p2435991/3628a5b44e3cdf885ce13ec3ca8ae98b/p2435991.jpg?format=auto&quality=70&f=650x0",
    category: "Women",
    rating: 2,
    size: 6,
    title: "Women Flip-Flops ",
    description:
      "Our surfer design teams have developed these Flip-Flops for water sports enthusiasts, for use before and after their sessions.",
    trending: false,
    orig_price: 499,
    sell_price: 300,
    delivery_days: 3,
    in_stock: true,
  },
  {
    _id: "a90720c3-c299-4d8c-828d-b662e99d3f93",
    index: 16,
    image:
      "https://assets.ajio.com/medias/sys_master/root/20221212/9GZS/63975904f997ddfdbdcda9a2/-473Wx593H-410354370-7xs-MODEL4.jpg",
    category: "Women",
    rating: 5,
    size: 5,
    title: "SUPERDRY",
    description: "Code Core Pool Slides",
    trending: true,
    orig_price: 2999,
    sell_price: 1649,
    delivery_days: 5,
    in_stock: true,
  },
  {
    _id: "89ccda7d-e849-4908-b212-8a7ad721c778",
    index: 17,
    image:
      "https://rukminim1.flixcart.com/image/832/832/l572ufk0/slipper-flip-flop/t/o/w/6-rg1-kbhub-white-original-imagfxhxfkj2yrng.jpeg?q=70",
    category: "Women",
    rating: 3,
    size: 4,
    title: "RADHIKA GROUP ",
    description: "Girls Slip On Slipper Flip Flop",
    trending: false,
    orig_price: 499,
    sell_price: 399,
    delivery_days: 4,
    in_stock: true,
  },
  {
    _id: "7c651a34-5f0d-4bf5-95c7-2461d42a20fe",
    index: 18,
    image: "https://m.media-amazon.com/images/I/51s05+7CyZL._UY575_.jpg",
    category: "Women",
    rating: 4,
    size: 6,
    title: "MIFUZI Girls' Flip-Flops & Slippers for Girls Kids ",
    description:
      "Stylish Fashionable Bow Home House Soft Cozy Indoor Cute Pink Slipper",
    trending: true,
    orig_price: 499,
    sell_price: 299,
    delivery_days: 3,
    in_stock: false,
  },
  {
    _id: "2ea09477-60c4-47ba-947c-38ebbeca98cf",
    index: 19,
    image:
      "https://rukminim1.flixcart.com/image/832/832/l2p23rk0/slipper-flip-flop/t/u/m/7-c-4-x-xiota-pink-original-imagdz7tvm4yum6y.jpeg?q=70",
    category: "Women",
    rating: 3.5,
    size: 7,
    title:
      "Collection Of Regular Wear Flower Printed Trendy Flats For Women's/Ladies/Girl's Slippers",
    description:
      "X Xiota Presents Lightweight & Breathable: Exclusive design and durable materials every step feels light and breezy.",
    trending: true,
    orig_price: 999,
    sell_price: 249,
    delivery_days: 4,
    in_stock: true,
  },
  {
    _id:"eb36f273-1918-44ca-b285-596daed9cde2",
    index: 20,
    image:
      "https://www.thilakawardhana.com/wp-content/uploads/2021/11/TA11128.jpg",
    category: "Women",
    rating: 4,
    size: 6,
    title: "WOMEN'S FLIP FLOP SLIPPERS",
    description:
      "Feel It the trend setter presents a gorgeous collection of ladies footwear",
    trending: true,
    orig_price: 599,
    sell_price: 249,
    delivery_days: 7,
    in_stock: false,
  },
  {
    _id: "d388f49b-69db-4967-8565-2081740853e9",
    index: 21,
    image: "https://images.meesho.com/images/products/106185006/snzvp_512.webp",
    category: "Kids",
    rating: 4,
    size: 3,
    title: "WABAKI PubG Flip flops/Slippers for kids",
    description:
      "Slipper Walk in Casual Style! This pair of slippers introduced to you has got both look and comfort",
    trending: true,
    orig_price: 599,
    sell_price: 299,
    delivery_days: 7,
    in_stock: false,
  },
  {
    _id: "661b5f78-b439-4b22-9b84-70e2ced020ed",
    index: 22,
    image: "https://m.media-amazon.com/images/I/71Uh1vHMgnL._UY695_.jpg",
    category: "Kids",
    rating: 5,
    size: 2,
    title: "Elecant Flip-Flop Slippers for kids boys",
    description:
      "Slippers are made of best quality of material Upper-PVC & Sole-PVC/Rubber.",
    trending: true,
    orig_price: 499,
    sell_price: 369,
    delivery_days: 5,
    in_stock: true,
  },
  {
    _id: "296fe3e6-ca71-4720-b363-202025d6e05f",
    index: 23,
    image:
      "https://www.jiomart.com/images/product/600x750/rvsn4gjrgc/marcolain-kids-flip-flop-slipper-for-boy-girl-product-images-rvsn4gjrgc-1-202207140249.jpg",
    category: "Kids",
    rating: 4,
    size: 1,
    title: "Marcolain Kids Flip-Flop Slipper",
    description:
      "kids slipper lunisex slippers l casual slippers l girls flip flop l boys slippers",
    trending: false,
    orig_price: 599,
    sell_price: 230,
    delivery_days: 6,
    in_stock: true,
  },
  {
    _id: "26c26991-271d-4cc3-b925-0b4aff72e8b2",
    index: 24,
    image:
      "https://images.jdmagicbox.com/rep/b2b/boys-flip-flop-slipper/boys-flip-flop-slipper-10.jpg",
    category: "Kids",
    rating: 3.5,
    size: 2,
    title: "Flip flops for kids",
    description:
      "Your kid will jump for joy on these cute flip flop. Broad strap & embossed footbed makes it stylish yet comfy.",
    trending: false,
    orig_price: 399,
    sell_price: 229,
    delivery_days: 3,
    in_stock: true,
  },
  {
    _id: "898d3f11-6033-4995-abb8-87e94b6b02bf",
    index: 25,
    image: "https://m.media-amazon.com/images/I/51kosdzo3aL.jpg",
    category: "Kids",
    rating: 5,
    size: 1,
    title: "Jenkan Cute Tom and Jerry casual flip flops for Baby kids",
    description:
      "Soft girls boys shower sandals slippers made of shock absorbing EVA foam are super lightweight and flexible,that is supportive and comfortable without weighing you down.",
    trending: true,
    orig_price: 799,
    sell_price: 346,
    delivery_days: 5,
    in_stock: false,
  },
  {
    _id: "8610a5cb-af52-4743-b47c-367ac89e21f3",
    index: 26,
    image:
      "https://staticm2.paragonfootwear.com/media/catalog/product/cache/3a88550bbe8642ae5e71ba6d62fc1851/h/w/hw0185-yellow_1.jpg",
    category: "Kids",
    rating: 3,
    size: 3,
    title: "Kids Yellow Stimulus Flip Flops",
    description:
      "The best slippers for kids, currently - these yellow flip-flops for children, from Paragon's Stimulus range",
    trending: true,
    orig_price: 499,
    sell_price: 299,
    delivery_days: 2,
    in_stock: true,
  },
  {
    _id: "35d26329-ea39-41ee-8ce4-8a1f27d26b11",
    index: 27,
    image: "https://rukminim1.flixcart.com/image/850/1000/xif0q/kids-slipper-flip-flop/3/n/h/-original-imaghfnhv2gh64m9.jpeg?q=90",
    category: "Kids",
    rating: 3,
    size: 1,
    title: "Flip-flops Slippers For Boys and Girls ",
    description:
      "Mag Creations Kid's Flip-flops Slippers For Boys and Girls Multi Colour Black & Blue",
    trending: false,
    orig_price: 499,
    sell_price: 199,
    delivery_days: 6,
    in_stock: true,
  },
  {
    _id: "d3e84dc7-fe61-474a-b6d5-0d5779b3abae",
    index: 28,
    image: "https://m.media-amazon.com/images/I/81WW+iGNY8S._UY695_.jpg",
    category: "Kids",
    rating: 4,
    size: 2,
    title: "Captain America Kids flip flop",
    description:
      "Marvel Avengers by toothless Boy's Kids Sky Blue Flip Flop Slipper",
    trending: false,
    orig_price: 449,
    sell_price: 319,
    delivery_days: 3,
    in_stock: true,
  },
  {
    _id: "62740de8-2c6a-4bf0-8bda-fc09170c5ca9",
    index: 29,
    image:
      "https://rukminim1.flixcart.com/image/832/832/kf0087k0/kids-slipper-flip-flop/e/j/f/4c-ora-n-blue-baby-aravon-original-imafvjv6s8syqpv7.jpeg?q=70",
    category: "Kids",
    rating: 4.5,
    size: 1,
    title: "ARAVON ",
    description: "Boys & Girls Slip On Slipper Flip Flop",
    trending: true,
    orig_price: 499,
    sell_price: 229,
    delivery_days: 2,
    in_stock: true,
  },
  {
    _id: "6f37c872-aa3f-4624-b096-7e1a91c29e0e",
    index: 30,
    image: "https://img.fruugo.com/product/4/61/450664614_max.jpg",
    category: "Kids",
    rating: 5,
    size: 2,
    title: "Wekity Kids Sandals Slippers",
    description:
      "Non Slip Sole --- Featured with cushioned sole and shoe-type pattern which can grip the floor very well for your toddler's protection from falling",
    trending: true,
    orig_price: 2199,
    sell_price: 1799,
    delivery_days: 8,
    in_stock: false,
  },
];

/**
 * Product Database can be added here.
 * You can add products of your wish with different attributes
 * */

// export const products = [
//   {
//     _id: uuid(),
//     title: "You Can WIN",
//     author: "Shiv Khera",
//     price: "5000",
//     categoryName: "non-fiction",
//   },
//   {
//     _id: uuid(),
//     title: "You are Winner",
//     author: "Junaid Qureshi",
//     price: "3000",
//     categoryName: "horror",
//   },
//   {
//     _id: uuid(),
//     title: "Think and Grow Rich",
//     author: "Shiv Khera",
//     price: "1000",
//     categoryName: "fiction",
//   },
// ];
